import type { Automation, GuestMessage, LanguageCode, Template } from "./types";

export const LANGUAGES: { code: LanguageCode; label: string }[] = [
  { code: "en", label: "English" },
  { code: "dv", label: "Dhivehi" },
  { code: "zh", label: "Chinese" },
  { code: "ru", label: "Russian" },
  { code: "de", label: "German" },
  { code: "it", label: "Italian" },
  { code: "fr", label: "French" },
  { code: "ar", label: "Arabic" },
  { code: "hi", label: "Hindi" },
];

export const DEMO_MESSAGES: GuestMessage[] = [
  {
    id: "m1",
    channel: "whatsapp",
    guestName: "Wei Chen",
    guestContact: "+86 138 0000 2211",
    body: "你好，我们想预订6月12-15日的双人房。有空房吗？价格含早餐吗？",
    detectedLanguage: "zh",
    translatedPreview:
      "Hello, we want to book a double room for June 12–15. Do you have availability? Is breakfast included in the price?",
    status: "unread",
    receivedAt: "2026-08-07T08:12:00.000Z",
    threadId: "t1",
  },
  {
    id: "m2",
    channel: "email",
    guestName: "Anna Müller",
    guestContact: "anna.mueller@email.de",
    subject: "Transfer from Velana Airport",
    body: "Guten Tag, wir landen am Freitag um 14:40. Können Sie einen Speedboat-Transfer zur Insel organisieren? Wie lange dauert die Fahrt und was kostet sie?",
    detectedLanguage: "de",
    translatedPreview:
      "Hello, we land on Friday at 14:40. Can you arrange a speedboat transfer to the island? How long does the trip take and what does it cost?",
    status: "unread",
    receivedAt: "2026-08-07T07:45:00.000Z",
    threadId: "t2",
  },
  {
    id: "m3",
    channel: "whatsapp",
    guestName: "Dmitry Volkov",
    guestContact: "+7 916 555 0199",
    body: "Здравствуйте! Подскажите, пожалуйста, есть ли Wi‑Fi в номерах и до скольки работает ресторан?",
    detectedLanguage: "ru",
    translatedPreview:
      "Hello! Please tell me, is there Wi‑Fi in the rooms and until what time does the restaurant work?",
    status: "read",
    receivedAt: "2026-08-06T18:20:00.000Z",
    threadId: "t3",
  },
  {
    id: "m4",
    channel: "email",
    guestName: "Sofia Rossi",
    guestContact: "sofia.rossi@mail.it",
    subject: "Check-in time and house rules",
    body: "Buongiorno, a che ora possiamo fare il check-in? Ci sono regole della casa da conoscere prima dell'arrivo? Grazie!",
    detectedLanguage: "it",
    translatedPreview:
      "Good morning, what time can we check in? Are there house rules we should know before arrival? Thank you!",
    status: "automated",
    receivedAt: "2026-08-06T14:05:00.000Z",
    threadId: "t4",
  },
  {
    id: "m5",
    channel: "whatsapp",
    guestName: "James Wright",
    guestContact: "+44 7700 900123",
    body: "Hi! Is snorkelling gear available at the guesthouse or should we bring our own? Also any good house reef nearby?",
    detectedLanguage: "en",
    translatedPreview:
      "Hi! Is snorkelling gear available at the guesthouse or should we bring our own? Also any good house reef nearby?",
    status: "replied",
    receivedAt: "2026-08-06T11:30:00.000Z",
    threadId: "t5",
  },
];

export const TEMPLATES: Template[] = [
  {
    id: "tpl-booking",
    name: "Booking availability reply",
    category: "booking",
    channels: ["whatsapp", "email"],
    body: "Bismillah — thank you for your enquiry.\n\nYes, we have availability for {{dates}}.\nRoom: {{room_type}}\nRate: {{price}} per night (breakfast {{breakfast}}).\n\nTo confirm, please share guest names and arrival flight details. We will hold the room for 24 hours.",
    variables: ["dates", "room_type", "price", "breakfast"],
  },
  {
    id: "tpl-transfer",
    name: "Airport transfer info",
    category: "transfer",
    channels: ["whatsapp", "email"],
    body: "Welcome to the Maldives!\n\nSpeedboat transfer from Velana Airport (MLE) to our island takes about {{duration}}.\nCost: {{transfer_price}} per person (shared) or {{private_price}} private boat.\n\nShare your flight number and arrival time and we will arrange pickup.",
    variables: ["duration", "transfer_price", "private_price"],
  },
  {
    id: "tpl-checkin",
    name: "Check-in instructions",
    category: "checkin",
    channels: ["whatsapp", "email"],
    body: "Assalamu alaikum — we look forward to welcoming you tomorrow.\n\nCheck-in: from {{checkin_time}}\nLocation: {{guesthouse_name}}, {{island}}\nWi‑Fi password will be given at reception.\n\nPlease bring passports for registration. Dinner is served {{dinner_time}}.",
    variables: ["checkin_time", "guesthouse_name", "island", "dinner_time"],
  },
  {
    id: "tpl-faq-wifi",
    name: "Wi‑Fi & meals FAQ",
    category: "faq",
    channels: ["whatsapp", "email"],
    body: "Yes — complimentary Wi‑Fi is available in all rooms and common areas.\n\nBreakfast: {{breakfast_hours}}\nLunch & dinner: à la carte / set menu at our restaurant until {{dinner_end}}.\n\nLet us know if you have dietary needs.",
    variables: ["breakfast_hours", "dinner_end"],
  },
  {
    id: "tpl-checkout",
    name: "Checkout & feedback",
    category: "checkout",
    channels: ["whatsapp", "email"],
    body: "Thank you for staying with {{guesthouse_name}}.\n\nCheckout is by {{checkout_time}}. Luggage storage is available if your flight is later.\n\nSafe travels — and if you enjoyed your stay, a quick review helps our island family a lot.",
    variables: ["guesthouse_name", "checkout_time"],
  },
];

export const AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    name: "Instant booking acknowledgement",
    enabled: true,
    trigger: "New booking enquiry on WhatsApp or Email",
    action: "Send translated booking reply template",
    channels: ["whatsapp", "email"],
    translateToGuestLanguage: true,
    templateId: "tpl-booking",
  },
  {
    id: "auto-2",
    name: "Pre-arrival check-in (24h before)",
    enabled: true,
    trigger: "Guest arrival date is tomorrow",
    action: "Send check-in instructions in guest language",
    channels: ["whatsapp", "email"],
    translateToGuestLanguage: true,
    templateId: "tpl-checkin",
  },
  {
    id: "auto-3",
    name: "Transfer FAQ auto-reply",
    enabled: true,
    trigger: "Message mentions airport / transfer / speedboat",
    action: "Reply with transfer template + translate",
    channels: ["whatsapp", "email"],
    translateToGuestLanguage: true,
    templateId: "tpl-transfer",
  },
  {
    id: "auto-4",
    name: "Wi‑Fi & meals FAQ",
    enabled: false,
    trigger: "Message mentions wifi / wi-fi / restaurant / breakfast",
    action: "Reply with FAQ template",
    channels: ["whatsapp", "email"],
    translateToGuestLanguage: true,
    templateId: "tpl-faq-wifi",
  },
];

export const GUESTHOUSE_DEFAULTS = {
  name: "Lagoon Pearl Guesthouse",
  island: "Maafushi",
  checkinTime: "14:00",
  checkoutTime: "11:00",
  breakfastHours: "07:00–09:30",
  dinnerTime: "19:00–21:00",
  dinnerEnd: "21:00",
  transferDuration: "45–60 minutes",
  transferPrice: "USD 25",
  privatePrice: "USD 150",
  roomType: "Deluxe double with AC",
  price: "USD 85",
  breakfast: "included",
};
